[package]
name = "webgpu-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29.0"
async-executor = "1.0"
wgpu = "23.0.1"
pollster = "0.2"
env_logger = "0.10"
log = "0.4"
bytemuck = { version = "1.12", features = ["derive"] }
glam = "0.23.0"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png"]