[package]
name = "webgpu-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.27"
async-executor = "1.0"
wgpu = "0.15.0"
pollster = "0.2"
env_logger = "0.10"
log = "0.4"
bytemuck = { version = "1.12", features = ["derive"] }
cgmath = "0.18.0"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png"]