[package]
name = "webgpu-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.27"
env_logger = "0.10.0"
log = "0.4"
wgpu = "0.15.0"
pollster = "0.2"
bytemuck = { version = "1.12", features = [ "derive" ] }